# Project information
site_name: Hawk Center Documentation
site_url: https://hawk-center.github.io/documentation/

# Repository
repo_name: hawk-center/documentation
repo_url: https://github.com/Hawk-Center/hawk-sdk

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Getting Started:
      - Installation: overview/getting-started.md
      - Development Setup: overview/development-setup.md
  - Architecture:
      - Overview: overview/architecture.md
      - Components: architecture/components.md
  - API Reference:
      - Model State Generator:
          - Base Classes: api/model-state-generator/base.md
          - Feature Engineering: api/model-state-generator/features.md
          - Configuration: api/model-state-generator/config.md
      - Trading Models:
          - Base Model: api/trading-models/base.md
          - Strategy Models: api/trading-models/strategies.md
          - Utilities: api/trading-models/utils.md
      - Portfolio Simulation:
          - Simulator: api/portfolio-simulation/simulator.md
          - Performance Metrics: api/portfolio-simulation/metrics.md
      - Model Aggregation:
          - Optimizer: api/model-aggregation/optimizer.md
          - Weight Allocation: api/model-aggregation/weights.md
      - Common:
          - Types: api/common/types.md
          - Enums: api/common/enums.md
          - Utils: api/common/utils.md
  - Contributing: CONTRIBUTING.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
      preserve_tabs: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - search

